INPUTO & OUTPUT

M7T1
'''
Fes on programa amb les següents accions:

Crea 4 variables: 
a una assigna-li el teu color preferit, 
a una altra el teu esport preferit, 
a una altra el teu lloc de naixement i 
a una altra el valor true si tens mascotes o false si no en tens.

Imprimeix aquestes 4 variables juntament amb la frase: 
"El meu color preferit és: X, el meu esport preferit és: Y, vaig néixer a: Z. Tinc mascotes? W", 
on X, Y, Z i W són els valors de les variables que has creat abans.

Demana 3 dades més mitjançant 3 prompts i pinta una frase amb els 3 valors que has demanat 
(pots inventar la temàtica de les dades que demanis).
'''

In [1]:
color = input("introduce tu color favorito: ")
deporte = input("introduce tu deporte favorito: ")
sitio_nacimiento = input("introduce tu lugar de nacimiento: ")
mascotas = bool(input("introduce si tienes mascotas (true/false): "))

print(f"El meu color preferit és: {color}, el meu esport preferit és: {deporte}, vaig néixer a: {sitio_nacimiento}. Tinc mascotes? {mascotas}")

edad = int(input("Cuantos años tienes?: "))
altura = float(input("Cuanto mides en metros?: "))
peso = float(input("Cuanto pesas?: "))

print(f"El usuario tiene {edad} años, mide {altura} cm y pesas {peso} kg. Tu IMC es: {peso/(altura**2)}")

El meu color preferit és: amarillo, el meu esport preferit és: futbol, vaig néixer a: barcelona. Tinc mascotes? True
El usuario tiene 31 años, mide 1.75 cm y pesas 78.0 kg. Tu IMC es: 25.46938775510204

CONDICIONALES

M7T2
'''
Crea un programa que pregunti a l'usuari quantes hores dorm de mitjana. 
Si dorm menys de 6 hores, el programa ha d'imprimir a la pantalla "Dorms poc", 
si és més gran o igual a 6 hores, el programa ha d'imprimir a la pantalla "Dorms molt".
'''

In [2]:
h_sueño = float(input("Cuantas horas duermes?: "))

if h_sueño < 6:
    print("duermes poco")
else:
    print("duermes mucho")

duermes mucho

M7T3
'''
Modifica el programa anterior i fes que la resposta segons les hores segueixi aquest algoritme:

Si el nombre és negatiu, el programa ha d'imprimir: "Un nombre negatiu d'hores no és possible."

Si el nombre està entre 0 i 4 (ambdós inclosos), el programa ha d'imprimir: "Dorms molt poc, això pot ser perjudicial per a la salut."

Si el nombre està entre 5 i 8 (ambdós inclosos), el programa ha d'imprimir: "Dorms una quantitat adequada per cuidar la teva salut."

Si el nombre és superior a 8, el programa ha d'imprimir: "Dorms molt! Potser és hora de plantejar-te si és necessari."
'''

In [3]:
h_sueño = float(input("Cuantas horas duermes?: "))

if h_sueño < 0:
    print("Un nombre negatiu d'hores no és possible.")
elif h_sueño >= 0 and h_sueño <= 4:
    print("Dorms molt poc, això pot ser perjudicial per a la salut.")
elif h_sueño >= 5 and h_sueño <=8:
    print("Dorms una quantitat adequada per cuidar la teva salut.") 
else:
    print("Dorms molt! Potser és hora de plantejar-te si és necessari.")

Dorms una quantitat adequada per cuidar la teva salut.

FUNCIONES

M7T4
'''
Crea una funció que sol·liciti a l’usuari el seu número favorit i mostri un missatge que digui: 
"El teu número favorit és X".
'''

In [4]:
def n_favorite():
    numero_favorito = int(input("Dime tu numero favorito "))
    print(f"Tu número favorito es {numero_favorito}")

n_favorite() # LLama a la funcion

Tu número favorito es 7

M7T5
'''
Crea una funció que rebi un text i retorni el text en majúscules. 
Demana un text a l’usuari i mostra el resultat amb la funció.
'''

In [5]:
def text_upper(text):
    new_text = text.upper()
    print(new_text)

text_lower = input("Escribe un texto: ")
text_upper(text_lower)

HPÑA

M7T6
'''
Demana dos números a l’usuari i crea una funció que retorni True si el primer número és més gran que el segon, 
i False en cas contrari.
'''

In [6]:
def front_number(x, y):
    if x>y:
        print(True)
    elif x<y:
        print(False)
    else:
        print("Tus números son iguales")

x = int(input("Introduce un número entero: "))
y = int(input("Introduce otr número entero: "))

front_number(x,y)

True

LISTAS Y DICCIONARIOS

M7T7 .1
'''
Crea una llista amb tres llibres inicials "El Quixot", "Hamlet" i "La metamorfosi".

Afegeix al final de la llista dos llibres més: "1984" i "Ulisses". Torna a imprimir la llista per veure els canvis.

Elimina "Hamlet" de la llista. Imprimeix la llista actualitzada.

Afegeix el llibre "Orgull i prejudici" a la tercera posició de la llista. Torna a imprimir la llista.
'''

In [7]:
my_list = ["El Quixot", "Hamlet", "La metamorfosi"]
my_list.append("1984")
my_list.append("Ulisses")
print(my_list)

['El Quixot', 'Hamlet', 'La metamorfosi', '1984', 'Ulisses']

M7T7 .2
''' 
Genera un diccionari amb els llibres de la llista resultant i el seu any de publicació:

El Quixot: 1605

La metamorfosi: 1915

1984: 1949

Ulisses: 1922

Orgull i prejudici: 1813

Imprimeix l'any de publicació d'Ulisses.

Afegeix al diccionari els teus dos llibres preferits amb el seu any de publicació.

Imprimeix el diccionari resultant.
'''

In [8]:
my_dict = {"El Quixot":1605,"La metamorfosi":1915, "1984":1949, "Ulisses":1922, "Orgull i prejudici":1813}
print(my_dict["Ulisses"])
my_dict["Juego de tronos"] = 2000
my_dict["Archivo de tormentas"] = 2010
print(my_dict)

1922
{'El Quixot': 1605, 'La metamorfosi': 1915, '1984': 1949, 'Ulisses': 1922, 'Orgull i prejudici': 1813, 'Juego de tronos': 2000, 'Archivo de tormentas': 2010}

M7T8
'''
Crea una funció que:

Demani a l’usuari 3 noms de ciutats, un per un.
Comprovi si cada ciutat conté la lletra 'E' o 'e' i té més de 5 lletres.
Si la ciutat compleix aquestes condicions, afegeix-la a una llista.
Quan hagi acabat, retorna la llista completa de ciutats que compleixen els requisits.
Finalment, crida la funció i imprimeix la llista completa.
'''

In [5]:
city_1 = input("Introduce el nombre de la ciudad 1: ")
city_2 = input("Introduce el nombre de la ciudad 2: ")
city_3 = input("Introduce el nombre de la ciudad 3: ")
cities = []

def function_city(city):
    if ("E" in city or "e"in city) and len(city) > 5:
        print(f"Tu ciudad ({city}) tiene una E/e")
        cities.append(city)

function_city(city_1)
function_city(city_2)
function_city(city_3)

print(cities)

Tu ciudad (Barcelona) tiene una E/e
Tu ciudad (Londres) tiene una E/e
Tu ciudad (Estocolmo) tiene una E/e
['Barcelona', 'Londres', 'Estocolmo']

BUCLES FOR & WHILE

M7T9
'''
Crea una funció que rebi per paràmetre el nombre de colors que l’usuari vol introduir. A continuació:

Demana els colors un per un amb un missatge del tipus: "Introdueix el color 1", "Introdueix el color 2", etc.
Desa cada color en una llista.
Quan tots els colors hagin estat introduïts, mostra la llista completa.
Finalment, abans de cridar la funció, es demana a l’usuari quants colors vol introduir.
'''

In [ ]:
def colores(numero):
    list_colores = []
    for i in range(numero):
        list_colores.append(input(f"Dime tu color favorito nº {i}"))
    print(list_colores)

veces = int(input("Cuantos colores quieres decir? "))
colores(veces)

['amarillo', 'rojo', 'azul']

M7T10
'''
Crea una funció que rebi una llista de números i retorni una nova llista amb només els números parells.

Després, crea una llista amb 10 números, i:

Imprimeix quants números parells hi ha.

Imprimeix quins són aquests números parells.
'''

In [11]:
def numeros_pares(lista):
    new_list = []
    for i in lista:
        if i % 2 == 0:
            new_list.append(i)
    
    print(f"La nueva lista de numeros pares es: {new_list} y tiene un total de {len(new_list)} números")

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numeros_pares(lista)

La nueva lista de numeros pares es: [2, 4, 6, 8, 10] y tiene un total de 5 números

M7T11
'''
Escriu un programa que faci el següent:

Demani a l’usuari que introdueixi una frase.

Utilitza una funció que rebi aquesta frase com a argument i retorni un diccionari amb:
   
Les paraules que apareixen a la frase com a claus.
   
El nombre de vegades que apareixen com a valors.

No utilitzis la funció integrada count() per comptar les paraules.

Finalment, mostra el diccionari per pantalla.
'''

In [ ]:
def frase_to_dict(frase):
    my_dict = {}
    for palabra in frase.lower().split():
        if palabra in my_dict:
            my_dict[palabra] += 1
        else:
            my_dict[palabra] = 1
    print(my_dict)

def frase_to_dict_mayu(frase):
    my_dict = {}
    for palabra in frase.split():
        if palabra in my_dict:
            my_dict[palabra] += 1
        else:
            my_dict[palabra] = 1
    print(my_dict)


frase = input("Introduce una frase: ") # hola Hola HOLA hola Hola HOLA

frase_to_dict(frase) 
frase_to_dict_mayu(frase)

{'hola': 6}
{'hola': 2, 'Hola': 2, 'HOLA': 2}

PANDAS & DATAFRAME

M7T12 (UDEMY_COUSES.CSV)
En aquest exercici, treballaràs amb el dataset Udemy_courses.csv utilitzant la biblioteca Pandas de Python. Realitzaràs diverses tasques d’exploració, filtres, agrupacions i modificació de columnes.

Carrega el dataset Udemy_courses.csv i respon a les següents preguntes:

In [3]:
# Importar Pandas y leer CSV
import pandas as pd
df = pd.read_csv("udemy_courses.csv")

In [ ]:
'''
1. Exploració de dades:

o Quantes columnes té el CSV, i quants registres?
o Quantes columnes de tipus enter té? I quantes de tipus decimal?
o Quin és el nombre de reviews màxim? I el de subcribers?
o Quina és la mitjana del ràting?
o Com has trobat totes aquestes respostes?
'''
# Esploració de dades:

df.info()
print(df.dtypes.value_counts())
print(f"El número de filas es: {df.shape[0]}")
print(f"El número de columnas es: {df.shape[1]}")
print(f"El número máximo de 'num_reviews' es: {df_data["num_reviews"].max()}")
print(f"El número máximo de 'num_subscribers' es: {df["num_subscribers"].max()}")
print(f"La media de 'rating' es: {df["rating"].mean()}")

<class 'pandas.DataFrame'>
RangeIndex: 3691 entries, 0 to 3690
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3691 non-null   int64
 1   title                3691 non-null   str
 2   url                  3691 non-null   str
 3   is_paid              3691 non-null   bool
 4   instructor_names     3691 non-null   str
 5   category             3691 non-null   str
 6   headline             3691 non-null   str
 7   num_subscribers      3691 non-null   int64
 8   rating               3691 non-null   float64
 9   num_reviews          3691 non-null   int64
 10  instructional_level  3691 non-null   str
 11  objectives           3691 non-null   str
 12  curriculum           3691 non-null   str
dtypes: bool(1), float64(1), int64(3), str(8)
memory usage: 349.8 KB
str        8
int64      3
bool       1
float64    1
Name: count, dtype: int64
El número de filas es: 3691
El número de columnas es: 13
El número máximo de 'num_reviews' es: 521219
El número máximo de 'num_subscribers' es: 1976866
La media de 'rating' es: 4.400516961202927

In [ ]:
'''
2. Filtres:

o Selecciona els cursos que tenen més de 100.000 subscriptors,
més d’un 4,7 de valoració i més de 90.000 ressenyes.
o Selecciona els cursos que tenen un "instructional level" de
principiants i que són de la categoria "Development".
'''
# Filtres

#Selecciona els cursos que tenen més de 100.000 subscriptors, més d’un 4,7 de valoració i més de 90.000 ressenyes
df[(df["num_subscribers"]>100000)&(df["rating"]>4.7)&(df["num_reviews"]>90000)]

#Selecciona els cursos que tenen un "instructional level" de principiants i que són de la categoria "Development"
df["instructional_level"].unique() # Beginner Level
df[(df["instructional_level"]=="Beginner Level")&(df["category"]=="Development")]

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum
16,1187016,The Ultimate MySQL Bootcamp: Go from SQL Begin...,https://www.udemy.com/course/the-ultimate-mysq...,True,Colt Steele,Development,"JUST COMPLETELY REDONE! Master SQL, Work With...",466263,4.656859,97617,Beginner Level,Create your own database or interact with exis...,"Introduction & 5 Minutes of SQL, This Course W..."
22,382002,C# Basics for Beginners: Learn C# Fundamentals...,https://www.udemy.com/course/csharp-tutorial-f...,True,Mosh Hamedani,Development,Master C# fundamentals in 6 hours - The most p...,249279,4.558962,72469,Beginner Level,Learn the fundamentals of C# and .NET Framewor...,"Introduction, What is this Course, About Me, A..."
31,1419182,SQL for Beginners: Learn SQL using MySQL and D...,https://www.udemy.com/course/sql-for-beginners...,True,"""Tim Buchalkas Learn Programming Academy"", Tim...",Development,Understand SQL using the MySQL database. Learn...,177176,4.579526,56721,Beginner Level,Have a detailed knowledge and understanding of...,"Course Introduction, Welcome to the Course, Sy..."
33,903378,The Python Bible™ | Everything You Need to Pro...,https://www.udemy.com/course/the-python-bible/,True,"Ziyad Yehia, Internet of Things Academy",Development,Build 11 Projects and go from Beginner to Pro ...,178286,4.582973,55235,Beginner Level,Gain a Solid & Unforgettable Understanding of ...,"Course Introduction, Course Structure, Install..."
42,1535678,Java Programming for Complete Beginners,https://www.udemy.com/course/java-programming-...,True,in28Minutes Official,Development,Java Programming for Beginners to Java Object ...,278410,4.544558,47186,Beginner Level,HANDS-ON with EXERCISES and PUZZLES: Learn Obj...,"Introduction to Course - Java Programming, Ste..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,2618738,Fortran For Beginners,https://www.udemy.com/course/fortran-for-begin...,True,Brad Richardson,Development,The basics of programming in Fortran,1503,3.913270,319,Beginner Level,The basics of programming in Fortran,"Introduction, Introduction, Initial Setup and ..."
3681,2445302,Django with GraphQL,https://www.udemy.com/course/django-with-graphql/,True,Krystian Czekalski,Development,Integrating GraphQL API with Django Framework,2056,3.506517,318,Beginner Level,Basics of Django Framework Basics of GraphQL H...,"Introduction, Introduction, Technology overvie..."
3685,4866490,2024 R Programming Bootcamp for Absolute Begin...,https://www.udemy.com/course/2022-r-programmin...,True,Toppers Bootcamp,Development,R Programming course suitable for Absolute Beg...,43628,4.197298,318,Beginner Level,Basics of R Programming Data Structures in R C...,"Basics of R Programming, Instructor's Note, In..."
3688,5018456,Web Design Course for Beginners to Intermediate,https://www.udemy.com/course/web-development-b...,True,Stephen Koel Soren,Development,"Learn the Basics of HTML, CSS, Wordpress and g...",27891,4.540056,317,Beginner Level,Tag Element Attributes Choosing Editor Visual ...,"Introduction, Introduction, Starting HTML, Nee..."
3690,4100126,Salesforce Development Master Training for Beg...,https://www.udemy.com/course/salesforce-develo...,True,Shrey Sharma,Development,Learn Salesforce Development from scratch and ...,2360,4.105863,317,Beginner Level,Salesforce Development Salesforce Certificatio...,"Course Introduction, Introduction, APEX Basics..."

In [23]:
'''
3. Agrupacions:

o Mostra el nombre de cursos per categoria.
o Mostra la mitjana de valoració per "instructional level" i “is_paid”.
'''
print(df.groupby("instructional_level").size())
df.groupby("instructional_level")["rating"].mean() # agrupar y calcular la media
print(df[df["is_paid"]==True].groupby("instructional_level")["rating"].mean()) #Solo hay True

instructional_level
All Levels            2056
Beginner Level        1063
Expert Level            46
Intermediate Level     526
dtype: int64
instructional_level
All Levels            4.405400
Beginner Level        4.385644
Expert Level          4.332760
Intermediate Level    4.417414
Name: rating, dtype: float64

In [34]:
'''
4. Modificació de columnes

o Afegir una columna nova al DataFrame anomenada “CursGran” que tingui com a valor True si la quantitat de subscriptors és més de 50.000 i False sinó.
o Crea un dataframe que NO contingui les últimes 6 columnes del dataframe original. Aquest nou dataframe guarda’l a una variable anomenada info_general.v 
'''

df["CursGran"] = df["num_subscribers"] > 50000
df["CursGran"].unique()

#info_general = df[df.columns[:6]]
info_general = df.iloc[:,:6]
info_general.info()

<class 'pandas.DataFrame'>
RangeIndex: 3691 entries, 0 to 3690
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                3691 non-null   int64
 1   title             3691 non-null   str
 2   url               3691 non-null   str
 3   is_paid           3691 non-null   bool
 4   instructor_names  3691 non-null   str
 5   category          3691 non-null   str
dtypes: bool(1), int64(1), str(4)
memory usage: 147.9 KB

M7T13 (HOSPITALS.CSV)
La nostra empresa es dedica a realitzar anàlisis de dades hospitalaries, i un client ens ha sol·licitat una eina per identificar dades bàsiques dels hospitals de cada comunitat autònoma de forma automàtica.

Per això, cal crear una funció que rebi dos paràmetres:

▪ Un DataFrame amb informació d’hospitals (com el del fitxer hospitals.csv).
▪ El nom d’una comunitat autònoma (com a cadena de text).

La funció ha de retornar un diccionari amb les següents dades relacionades amb la comunitat autónoma indicada:

▪ Quantitat d’hospitals que hi ha a la comunitat autònoma
▪ Quantitat d’hospitals que hi ha a la comunitat autónoma que tenen més del 50% d’ocupació
▪ Indice_satifaccion màxim de la comunitat autónoma
▪ Indice_satifaccion mínim de la comunitat autònoma
▪ Total de llits a la comunitat autónoma
▪ Mitjana de l’index de satisfacció dels hospitals de la comunitat autònoma

Finalment, carrega el fitxer adjunt amb aquesta instrucció: data = pd.read_csv("arxiu csv", sep = ";", encoding = "latin-1") i executa la funció per a diverses comunitats autònomes i mostra els resultats obtinguts.

In [ ]:
df = pd.read_csv("hospitals.csv", sep=";", encoding="ISO-8859-1")
df.info()
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   hospital_id                 170 non-null    int64
 1   nombre                      170 non-null    str
 2   localidad                   170 non-null    str
 3   provincia                   170 non-null    str
 4   comunidad_autonoma          170 non-null    str
 5   presupuesto_anual_millones  170 non-null    float64
 6   num_camas                   170 non-null    int64
 7   num_medicos                 170 non-null    int64
 8   indice_satisfaccion         170 non-null    float64
 9   porcentaje_ocupacion        170 non-null    float64
dtypes: float64(3), int64(3), str(4)
memory usage: 13.4 KB

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4

In [37]:
def info_hospi(df_data, ccaa_name):
    print(f"Nº de hospitales en {ccaa_name}: {df_data[df_data["comunidad_autonoma"]==ccaa_name].shape[0]}") # Nº de hospitales
    print(f"Nº de hospitales con más del 50% de ocupacion en {ccaa_name}: {df_data [(df_data ["comunidad_autonoma"]==ccaa_name)&(df_data ["porcentaje_ocupacion"]>50)].shape[0]}") # Nº hospitales con >50% ocupacion
    print(f"Máximo del indice de satisfaccion en {ccaa_name}: {df_data [df_data ["comunidad_autonoma"]==ccaa_name]["indice_satisfaccion"].max()}") #Indice máx por ccaa
    print(f"Mínimo del indice de satisfaccion en {ccaa_name}: {df_data [df_data ["comunidad_autonoma"]==ccaa_name]["indice_satisfaccion"].min()}") #Indice min por ccaa
    print(f"Total de camas en {ccaa_name}: {df_data [df_data ["comunidad_autonoma"]==ccaa_name]["num_camas"].sum()}") # Total camas por ccaa
    print(f"Media del indice de satisfaccion en {ccaa_name}: {round(df_data [df_data ["comunidad_autonoma"]==ccaa_name]["indice_satisfaccion"].mean(),2)}") #Media indice satisfaccion por ccaa

In [38]:
for i in df["comunidad_autonoma"].unique():
    info_hospi(df, i)
    print("")

Nº de hospitales en Andalucia: 31
Nº de hospitales con más del 50% de ocupacion en Andalucia: 31
Máximo del indice de satisfaccion en Andalucia: 9.8
Mínimo del indice de satisfaccion en Andalucia: 1.6
Total de camas en Andalucia: 16201
Media del indice de satisfaccion en Andalucia: 5.51

Nº de hospitales en Aragon: 10
Nº de hospitales con más del 50% de ocupacion en Aragon: 10
Máximo del indice de satisfaccion en Aragon: 9.2
Mínimo del indice de satisfaccion en Aragon: 4.7
Total de camas en Aragon: 4661
Media del indice de satisfaccion en Aragon: 6.86

Nº de hospitales en Asturias: 6
Nº de hospitales con más del 50% de ocupacion en Asturias: 6
Máximo del indice de satisfaccion en Asturias: 9.7
Mínimo del indice de satisfaccion en Asturias: 2.0
Total de camas en Asturias: 1980
Media del indice de satisfaccion en Asturias: 7.38

Nº de hospitales en Islas Baleares: 7
Nº de hospitales con más del 50% de ocupacion en Islas Baleares: 7
Máximo del indice de satisfaccion en Islas Baleares: 8.2
Mínimo del indice de satisfaccion en Islas Baleares: 1.3
Total de camas en Islas Baleares: 3947
Media del indice de satisfaccion en Islas Baleares: 5.3

Nº de hospitales en Islas Canarias: 9
Nº de hospitales con más del 50% de ocupacion en Islas Canarias: 9
Máximo del indice de satisfaccion en Islas Canarias: 9.2
Mínimo del indice de satisfaccion en Islas Canarias: 3.9
Total de camas en Islas Canarias: 4858
Media del indice de satisfaccion en Islas Canarias: 7.06

Nº de hospitales en Cantabria: 4
Nº de hospitales con más del 50% de ocupacion en Cantabria: 4
Máximo del indice de satisfaccion en Cantabria: 7.2
Mínimo del indice de satisfaccion en Cantabria: 2.6
Total de camas en Cantabria: 3166
Media del indice de satisfaccion en Cantabria: 4.57

Nº de hospitales en Castilla-La Mancha: 11
Nº de hospitales con más del 50% de ocupacion en Castilla-La Mancha: 11
Máximo del indice de satisfaccion en Castilla-La Mancha: 9.3
Mínimo del indice de satisfaccion en Castilla-La Mancha: 1.2
Total de camas en Castilla-La Mancha: 4958
Media del indice de satisfaccion en Castilla-La Mancha: 5.25

Nº de hospitales en Castilla y Leon: 11
Nº de hospitales con más del 50% de ocupacion en Castilla y Leon: 11
Máximo del indice de satisfaccion en Castilla y Leon: 9.3
Mínimo del indice de satisfaccion en Castilla y Leon: 2.3
Total de camas en Castilla y Leon: 5948
Media del indice de satisfaccion en Castilla y Leon: 6.05

Nº de hospitales en Cataluña: 16
Nº de hospitales con más del 50% de ocupacion en Cataluña: 16
Máximo del indice de satisfaccion en Cataluña: 7.3
Mínimo del indice de satisfaccion en Cataluña: 1.1
Total de camas en Cataluña: 8955
Media del indice de satisfaccion en Cataluña: 4.93

Nº de hospitales en Comunidad Valenciana: 12
Nº de hospitales con más del 50% de ocupacion en Comunidad Valenciana: 12
Máximo del indice de satisfaccion en Comunidad Valenciana: 9.9
Mínimo del indice de satisfaccion en Comunidad Valenciana: 3.3
Total de camas en Comunidad Valenciana: 6547
Media del indice de satisfaccion en Comunidad Valenciana: 6.26

Nº de hospitales en Extremadura: 7
Nº de hospitales con más del 50% de ocupacion en Extremadura: 7
Máximo del indice de satisfaccion en Extremadura: 7.9
Mínimo del indice de satisfaccion en Extremadura: 1.2
Total de camas en Extremadura: 2805
Media del indice de satisfaccion en Extremadura: 4.5

Nº de hospitales en Galicia: 11
Nº de hospitales con más del 50% de ocupacion en Galicia: 11
Máximo del indice de satisfaccion en Galicia: 8.4
Mínimo del indice de satisfaccion en Galicia: 1.2
Total de camas en Galicia: 6164
Media del indice de satisfaccion en Galicia: 5.85

Nº de hospitales en Comunidad de Madrid: 9
Nº de hospitales con más del 50% de ocupacion en Comunidad de Madrid: 9
Máximo del indice de satisfaccion en Comunidad de Madrid: 9.3
Mínimo del indice de satisfaccion en Comunidad de Madrid: 1.1
Total de camas en Comunidad de Madrid: 4409
Media del indice de satisfaccion en Comunidad de Madrid: 4.29

Nº de hospitales en Region de Murcia: 6
Nº de hospitales con más del 50% de ocupacion en Region de Murcia: 6
Máximo del indice de satisfaccion en Region de Murcia: 9.4
Mínimo del indice de satisfaccion en Region de Murcia: 1.9
Total de camas en Region de Murcia: 3790
Media del indice de satisfaccion en Region de Murcia: 4.87

Nº de hospitales en Navarra: 4
Nº de hospitales con más del 50% de ocupacion en Navarra: 4
Máximo del indice de satisfaccion en Navarra: 9.0
Mínimo del indice de satisfaccion en Navarra: 6.8
Total de camas en Navarra: 2617
Media del indice de satisfaccion en Navarra: 7.78

Nº de hospitales en Pais Vasco: 11
Nº de hospitales con más del 50% de ocupacion en Pais Vasco: 11
Máximo del indice de satisfaccion en Pais Vasco: 9.3
Mínimo del indice de satisfaccion en Pais Vasco: 1.6
Total de camas en Pais Vasco: 6689
Media del indice de satisfaccion en Pais Vasco: 6.19

Nº de hospitales en La Rioja: 3
Nº de hospitales con más del 50% de ocupacion en La Rioja: 3
Máximo del indice de satisfaccion en La Rioja: 3.6
Mínimo del indice de satisfaccion en La Rioja: 2.3
Total de camas en La Rioja: 1587
Media del indice de satisfaccion en La Rioja: 3.1

Nº de hospitales en Ceuta: 1
Nº de hospitales con más del 50% de ocupacion en Ceuta: 1
Máximo del indice de satisfaccion en Ceuta: 6.3
Mínimo del indice de satisfaccion en Ceuta: 6.3
Total de camas en Ceuta: 208
Media del indice de satisfaccion en Ceuta: 6.3

Nº de hospitales en Melilla: 1
Nº de hospitales con más del 50% de ocupacion en Melilla: 1
Máximo del indice de satisfaccion en Melilla: 6.5
Mínimo del indice de satisfaccion en Melilla: 6.5
Total de camas en Melilla: 652
Media del indice de satisfaccion en Melilla: 6.5

M7T14 (HOSPITALS(1).CSV)
La nostra empresa está colaborant amb el colectiu de metges per veure quina càrrega de treball están patint. La idea es veure quins metges han de donar suport a més pacients i quins sembla que tenen menys persones a càrrec.

Per fer-ho, ens han proporcionat un conjunt de dades (hospitals.csv) que conté informació detallada sobre els hospitals del país.

Crea una funció en Python que rebi com a paràmetres:

▪ Un DataFrame amb dades d’hospitals.
▪ El nombre n d’hospitals que es volen obtenir com a resultat.

La funció ha de calcular, per a cada hospital la càrrega de treball dels metges, utilitzant la següent fórmula: càrrega treball metge = num_llits /num_metges * percentatge ocupació

La funció ha de retornar els n hospitals amb més càrrega de treball per metge.

Executa la funció per obtenir 10 hospitals i després per obtenir-ne 20.

In [56]:
def carga_hospital(df_data, n_hospitales):
    df_data["carga_trabajo"] = df_data["num_camas"]/df_data["num_medicos"]*df_data["porcentaje_ocupacion"]
    print(df_data.nlargest(n_hospitales,"carga_trabajo").sort_values("carga_trabajo", ascending=False)[["nombre","carga_trabajo"]])

In [57]:
print("Top 10 hospitales con más carga de trabajo por médico")
carga_hospital(df, 10)
print("\nTop 20 hospitales con más carga de trabajo por médico")
carga_hospital(df, 20)

Top 10 hospitales con más carga de trabajo por médico
                                        nombre  carga_trabajo
66                     Hospital de Sierrallana    5677.200000
57           Hospital Doctor Jose Molina Orosa    3279.400000
14     Hospital Universitario Virgen del Rocio    2612.384211
2        Hospital Universitario Puerta del Mar    2124.093750
104      Hospital de Tortosa Verge de la Cinta    1845.658333
15      Hospital Universitario Virgen Macarena    1641.280000
50                       Hospital Mateu Orfila    1577.352632
5                   Hospital Infanta Margarita    1262.866667
99   Hospital d'Olot i Comarcal de la Garrotxa    1101.660000
77   Hospital General Nuestra Señora del Prado     960.960000

Top 20 hospitales con más carga de trabajo por médico
                                           nombre  carga_trabajo
66                        Hospital de Sierrallana    5677.200000
57              Hospital Doctor Jose Molina Orosa    3279.400000
14        Hospital Universitario Virgen del Rocio    2612.384211
2           Hospital Universitario Puerta del Mar    2124.093750
104         Hospital de Tortosa Verge de la Cinta    1845.658333
15         Hospital Universitario Virgen Macarena    1641.280000
50                          Hospital Mateu Orfila    1577.352632
5                      Hospital Infanta Margarita    1262.866667
99      Hospital d'Olot i Comarcal de la Garrotxa    1101.660000
77      Hospital General Nuestra Señora del Prado     960.960000
165                            Hospital San Pedro     811.476923
87                 Complejo Asistencial de Zamora     709.900794
3                               Hospital de Jerez     699.841071
130                             Hospital da Costa     607.265306
64   Hospital Universitario Marques de Valdecilla     581.752941
26                          Hospital de Antequera     574.386420
162                      Hospital de Santa Marina     539.613423
74                       Hospital de Puerto Llano     525.024706
121                             Hospital de Zafra     518.077311
10                 Hospital Universitario de Jaen     486.015190